### ISSUE TITLE
If you swap pouches while wearing them, then the items of one are duped to another.

### ISSUE THREAD

**Issue by MrTonyNeon** [Cynosphere-mc/Scout#12]
https://user-images.githubusercontent.com/84841244/178348640-4e058645-245d-431d-86e5-162838012fbe.mp4

Steps to dupe items:
1) put items you wanna dupe in one pouch
2) take other pouch from trinkets slot
3) left click with it on other pouch with items you wanna dupe
4) then put pouch which you are holding on its slot
5) voila, you duped items.

P.s. after that, the pouches can be taken off and put on again in order to repeat the process.

**Comment by Cynosphere** [comment]
Will be fixed when 1.1.0 releases. I have other plans for that release thus why it isn't just a bugfix release.
