### ISSUE TITLE
some bugs in the spectator gamemode

### ISSUE THREAD

**Issue by Gokotta4229** [Cynosphere-mc/Scout#17]
Alright,Hello, I'm a minecraft player from China,Maybe my words don't sound very fluent. I use machine translation because of my English level.
First of all,I like your works and creativity very much. I also used this mod in the early stage of my Survival Archive.I can't find “scout ”on Chinese forums (mcbbs, MC Encyclopedia). I downloaded an  modpack and found such a creative mod in it.I also hope that more of your works can be played by Chinese players.
Second,While opening the box,I can't take things out of the upgraded satchel or upgraded pouch directly，I think this interface is similar to the backpack interface and can be displayed.

<img width="1280" alt="2022-08-16" src="https://user-images.githubusercontent.com/111302236/184680033-b5a1e21c-1427-49a3-9e5b-33864c841a3b.png">
     Then,I found a huge bug from this mod：When I enter the spectator gamemode and open the backpack, I put the contents of the backpack into upgraded satchel or upgraded pouch,I found that it had the effect of copying
<img width="1280" alt="2022-08-16 (1)" src="https://user-images.githubusercontent.com/111302236/184681361-9624cf64-23d3-4b2b-a87b-2d30ef32669a.png">
     But when I tried to take out the contents of the upgraded satchel or upgraded pouch, they disappeared。So I tried the reverse operation，When I enter the spectator gamemode and put the contents of the upgraded satchel or upgraded pouch into backpack,I found that the item disappeared, but not completelyy
<img width="1280" alt="2022-08-16 (2)" src="https://user-images.githubusercontent.com/111302236/184681813-b5f72e46-0f28-48de-a3bc-972294275a5e.png">
     As you can see, these 12 stones actually exist. I did get them after double clicking the stones in the backpack, but they were not displayed

**Comment by Cynosphere** [comment]
I want to address the first issue at some point in the future but it requires reworking the slots and rendering and its just an annoyance at the current moment.

All the spectator stuff I'm going to count as invalid since the mod was designed for survival anyways. If someone wants to dupe items with something like Carpet's camera mode, that's on them personally.
