### ISSUE TITLE
Crash when clicking in inventory gui

### ISSUE THREAD

**Issue by kiishiio** [Cynosphere-mc/Scout#2]
crash when i click in a slot from inventory gui

crashlog:
https://gist.github.com/NotTheRealRoKur0/9a4a494c1c0919265e262d3f1acd9ab0

and would it be also possible to add a 3d model to the bag?

**Comment by Cynosphere** [comment]
Caused by Tiny Item Animations. It's bypassing my mixin catch-all by abstracting out its mixin functions to another class.

----

> and would it be also possible to add a 3d model to the bag?

The satchel already has one for when worn.

**Comment by kiishiio** [comment]
is there a way to compat?

and would it be possible to add one for the bag aswell?
could i do it myself via resourcepack, would that work?

**Comment by kiishiio** [comment]
ohh did one for the pouch too :)
looks kinda cute ngl
![image](https://github.com/Cynosphere-mc/Scout/assets/98748787/431b7321-60f1-4352-ba2b-7018af8144ee)
