### ISSUE TITLE
REI initialization startup warnings

### ISSUE THREAD

**Issue by dadoirie** [Cynosphere-mc/Scout#3]
Warning: The entrypoint used by Scout, "rei" is deprecated and will be removed in the future versions of Roughly Enough Items. Please use "rei_server", "rei_client" or "rei_common" instead.

This warning pops up every time when starting up Minecraft (which is a bit annoying to be fair).

**Comment by Cynosphere** [comment]
1.18 or 1.19? I don't remember seeing this in 1.18 so I'm guessing its something changed in 1.19.

**Comment by dadoirie** [comment]
My bad ... forgot to mention that it is 1.19 (fabric)
