### ISSUE TITLE
Sometimes Satchel/Pouch Inventory Does not update (can cause lost item if un-equiped)

### ISSUE THREAD

**Issue by ardissaps** [Cynosphere-mc/Scout#6]
When we insert item to the pouch, it sometimes does not update the inventory preview. Only sometimes, not always, but when it happen, it will never update the item inside when un-equiped (the missing item will lost forever).
![image](https://user-images.githubusercontent.com/82106625/175464705-b6084591-59a7-4afb-80ef-2500de80e633.png)

bonus : minor visual glitch with Inventory Tabs mods.
https://modrinth.com/mod/inventory-tabs-updated

**Comment by Dylanthalus** [comment]
i think that's what happened to my diamond shovel and diamond axe. somehow the game replicated the contents of the other pouch when i swapped the two pouches and then reopened my inventory. Oddly iron pickaxes I thought lost had returned but somehow I lost my diamond shovel and diamond axe which were in a pouch.

**Comment by ardissaps** [comment]
it is on creative mode but switched to survival for testing, it is hard to replicate coz it is not happening all the time, but also not so rare.
